# Site settings
title: SpecMatrix
email: your-email@example.com
description: >- 
  Your site description here
baseurl: ""
url: ""
github_username: Belligerently

# Build settings
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Theme customization
show_downloads: false

# Navigation
header_pages:
  - readme.md
  - docs.md
  - guide.md
  - about.md

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/