# Site settings
title: Your Site Name
email: your-email@example.com
description: >- 
  Your site description here
baseurl: ""
url: ""
github_username: yourusername

# Build settings
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Theme customization
show_downloads: false

# Custom settings
header_pages:
  - about.md
  - docs.md