# Site settings
title: SpecMatrix
email: spec.matrix.app@gmail.com
description: >- 
  SpecMatrix is an iOS application designed to provide an innovative solution for users
  to monitor their system components and specs
url: "https://belligerently.github.io"
baseurl: "/SpecMatrix"
github_username: Belligerently

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Minimal Mistakes theme settings
minimal_mistakes_skin: "dark" # options: air, contrast, dark, dirt, mint, sunrise
locale: "en-US"
title_separator: "|"
subtitle: "iOS System Monitor"
name: "Zachary Aflalo"
repository: "Belligerently/SpecMatrix"

# GitHub settings
github: [metadata]
repository: Belligerently/SpecMatrix
github_repository: Belligerently/SpecMatrix

# Site Author
author:
  name: "Zachary Aflalo"
  avatar: "/assets/images/placeholder-avatar.png"
  bio: "iOS Developer"
  location: "United States"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Belligerently"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:spec.matrix.app@gmail.com"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "#"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Belligerently"

# Include files and directories
include:
  - _pages
  - _data
  - assets/js/components

# Scripts to include in head
head_scripts:
  - https://unpkg.com/react@18/umd/react.production.min.js
  - https://unpkg.com/react-dom@18/umd/react-dom.production.min.js

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-github-metadata
  - jekyll-remote-theme

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "docs"
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"

# Masthead (Navigation) settings
masthead_title: "SpecMatrix"

# Additional Jekyll settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge